import React from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "./Layout.module.css";

const Layout = ({ children, title = "World Stats" }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Link href="/">
          <img
            src="https://i.imgur.com/Y28l856.png"
            alt="World Stats logo"
            width="150px"
          />
        </Link>
      </header>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>Upgrade Hub - 2021</footer>
    </div>
  );
};

export default Layout;
